version: '3.7'

services:
  web:
    build:
      context: ./django
      dockerfile: Dockerfile
    command: >
        bash -c "python manage.py collectstatic --no-input --clear &&
        python manage.py makemigrations --noinput &&
        python manage.py migrate --no-input && 
        gunicorn apsviz_gauges.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/django/web/staticfiles
      - media_volume:/home/django/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: timescale/timescaledb-postgis:latest-pg13
    ports:
      - 5432:${SQL_PORT:-5432}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ingest_data:/home/DataIngesting
    env_file:
      - ./.env.db
  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - static_volume:/home/django/web/staticfiles
      - media_volume:/home/django/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  ingest_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /projects/ees/TDS/DataIngesting 
  static_volume:
  media_volume:
